# Generated by Django 4.2.2 on 2023-07-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_article_remove_user_id_user_id_user_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default='Miembro', max_length=11),
        ),
    ]
