# Generated by Django 4.2.2 on 2023-07-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
