# Generated by Django 4.2.2 on 2023-07-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
