# Generated by Django 4.2.2 on 2023-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='user_phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
