# Generated by Django 4.2.2 on 2023-07-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_remove_users_phone_users_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_phone',
            new_name='phone',
        ),
    ]
