# Generated by Django 4.2.2 on 2023-07-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_rename_user_phone_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
