# Generated by Django 4.2.2 on 2023-07-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_remove_comments_articulo_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
